// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe6Z-BUvHubt6lPvOhEqg2VCL2SqIETLk',
    appId: '1:261936904359:web:1b0ab5827d7166cd138382',
    messagingSenderId: '261936904359',
    projectId: 'quizapp-ecf8a',
    authDomain: 'quizapp-ecf8a.firebaseapp.com',
    storageBucket: 'quizapp-ecf8a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_ZYvPg4pvU1N3c5ztP7MKxetfXmHaA7g',
    appId: '1:261936904359:android:13003f1b355a26df138382',
    messagingSenderId: '261936904359',
    projectId: 'quizapp-ecf8a',
    storageBucket: 'quizapp-ecf8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYfqsrGGQLRpmJWU0ZzZb4Gu3QS7fGLpk',
    appId: '1:261936904359:ios:bce9a372033f2bb9138382',
    messagingSenderId: '261936904359',
    projectId: 'quizapp-ecf8a',
    storageBucket: 'quizapp-ecf8a.appspot.com',
    iosClientId: '261936904359-hj89g2tm7vbj4r86kqa1se4m3rs6cejd.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQuiz',
  );
}
